# Generated by Django 2.1.4 on 2018-12-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('id_utilisateur', models.IntegerField()),
                ('etat', models.CharField(max_length=20)),
            ],
        ),
    ]
